loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[31mWARNING: NO MODEL LOADED !!!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
  File "train_net.py", line 69, in <module>
    main()
  File "train_net.py", line 66, in main
    train(network, cfg)
  File "train_net.py", line 50, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/deep/1-POJECT/e2ec/e2ec/train/trainer/trainer.py", line 37, in train
    output, loss, loss_stats = self.network(batch)
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/deep/1-POJECT/e2ec/e2ec/train/trainer/snake.py", line 21, in forward
    output = self.net(batch['inp'], batch)
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/deep/1-POJECT/e2ec/e2ec/network/make_network.py", line 29, in forward
    output, cnn_feature = self.dla(x)
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/deep/1-POJECT/e2ec/e2ec/network/backbone/dla.py", line 473, in forward
    x = self.base(x)
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/deep/1-POJECT/e2ec/e2ec/network/backbone/dla.py", line 289, in forward
    x = getattr(self, 'level{}'.format(i))(x)
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/deep/anaconda3/envs/e2ec/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 526.00 MiB (GPU 3; 11.91 GiB total capacity; 1.24 GiB already allocated; 168.06 MiB free; 1.26 GiB reserved in total by PyTorch)